export { default as Hero} from './Hero'
export { default as Navbar} from './Navbar'
export { default as Offers } from './Offers'
export { default as Menu } from './Menu'
export { default as Discover } from './Discover'
export { default as Reservation } from './Reservation'
export { default as Footer } from './Footer'
export { default as ToggleButton} from './ToggleButton'